package com.mycompany.rn.project;

import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karol
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    NeuralNetwork NN;
    ArrayList<ArrayList<Double>> matrixAttributesTest;

    public Form() {
        initComponents();
        ButtonInitTraining.setEnabled(false);
        ButtonChoseFile2.setEnabled(false);
        ButtonInitTest.setEnabled(false);
        RadioButtonLogistic.setSelected(true);
        RadioButtonMaxError.setSelected(true);
        NN = null;
        matrixAttributesTest = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupFunction = new javax.swing.ButtonGroup();
        buttonGroupParada = new javax.swing.ButtonGroup();
        Panel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        ButtonChoseFile = new javax.swing.JButton();
        LabelFileName = new javax.swing.JLabel();
        ButtonInitTraining = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        LabelAttributesAmount = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        LabelClassAmount = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        RadioButtonTH = new javax.swing.JRadioButton();
        RadioButtonMaxError = new javax.swing.JRadioButton();
        RadioButtonNumberIterations = new javax.swing.JRadioButton();
        TextFieldMaxError = new javax.swing.JTextField();
        TextFieldNumberOfIterations = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        ButtonChoseFile2 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        ButtonInitTest = new javax.swing.JButton();
        LabelFileName2 = new javax.swing.JLabel();
        TextFieldOcultLayer = new javax.swing.JTextField();
        RadioButtonLogistic = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        TextFieldLearningRate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rede Neural");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(453, 600));
        setPreferredSize(new java.awt.Dimension(453, 556));
        setSize(new java.awt.Dimension(453, 600));

        Panel.setBackground(new java.awt.Color(255, 255, 255));
        Panel.setPreferredSize(new java.awt.Dimension(453, 556));

        jLabel19.setText("Escolha o arquivo de treinamento");

        ButtonChoseFile.setBackground(new java.awt.Color(51, 51, 255));
        ButtonChoseFile.setForeground(new java.awt.Color(255, 255, 255));
        ButtonChoseFile.setText("Escolher Arquivo");
        ButtonChoseFile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonChoseFile.setBorderPainted(false);
        ButtonChoseFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonChoseFile.setPreferredSize(null);
        ButtonChoseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonChoseFileActionPerformed(evt);
            }
        });

        LabelFileName.setForeground(new java.awt.Color(255, 0, 0));
        LabelFileName.setText("Nome do arquivo . extesão");

        ButtonInitTraining.setBackground(new java.awt.Color(51, 51, 255));
        ButtonInitTraining.setForeground(new java.awt.Color(255, 255, 255));
        ButtonInitTraining.setText("Iniciar treinamento");
        ButtonInitTraining.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonInitTraining.setBorderPainted(false);
        ButtonInitTraining.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonInitTraining.setPreferredSize(null);
        ButtonInitTraining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInitTrainingActionPerformed(evt);
            }
        });

        jLabel20.setText("Número de neurônios na camada de entrada");

        LabelAttributesAmount.setText("0");

        jLabel21.setText("Número de neurônios na camada de saída");

        LabelClassAmount.setText("0");

        jLabel22.setText("Número de neurônios na camada oculta");

        RadioButtonTH.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupFunction.add(RadioButtonTH);
        RadioButtonTH.setText("Tangente hiperbólica");
        RadioButtonTH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonTHActionPerformed(evt);
            }
        });

        RadioButtonMaxError.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupParada.add(RadioButtonMaxError);
        RadioButtonMaxError.setText("Erro máximo");
        RadioButtonMaxError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonMaxErrorActionPerformed(evt);
            }
        });

        RadioButtonNumberIterations.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupParada.add(RadioButtonNumberIterations);
        RadioButtonNumberIterations.setText("Número de iterações");
        RadioButtonNumberIterations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonNumberIterationsActionPerformed(evt);
            }
        });

        TextFieldMaxError.setText("0.001");
        TextFieldMaxError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldMaxErrorActionPerformed(evt);
            }
        });

        TextFieldNumberOfIterations.setText("500");
        TextFieldNumberOfIterations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNumberOfIterationsActionPerformed(evt);
            }
        });

        jLabel23.setText("Escolha o arquivo de teste");

        ButtonChoseFile2.setBackground(new java.awt.Color(51, 51, 255));
        ButtonChoseFile2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonChoseFile2.setText("Escolher Arquivo");
        ButtonChoseFile2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonChoseFile2.setBorderPainted(false);
        ButtonChoseFile2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonChoseFile2.setPreferredSize(null);
        ButtonChoseFile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonChoseFile2ActionPerformed(evt);
            }
        });

        jLabel24.setText("Matriz de confusão: ");

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0", "0", "0", "0", "0"},
                {"0", "0", "0", "0", "0"},
                {"0", "0", "0", "0", "0"},
                {"0", "0", "0", "0", "0"},
                {"0", "0", "0", "0", "0"}
            },
            new String [] {
                "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table.setGridColor(new java.awt.Color(255, 255, 255));
        Table.setRowHeight(15);
        Table.setSelectionBackground(new java.awt.Color(51, 51, 255));
        Table.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(Table);

        jLabel25.setText("Desejado");

        jLabel26.setText("Obtido");

        ButtonInitTest.setBackground(new java.awt.Color(255, 0, 0));
        ButtonInitTest.setForeground(new java.awt.Color(255, 255, 255));
        ButtonInitTest.setText("Testar");
        ButtonInitTest.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonInitTest.setBorderPainted(false);
        ButtonInitTest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonInitTest.setPreferredSize(null);
        ButtonInitTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInitTestActionPerformed(evt);
            }
        });

        LabelFileName2.setForeground(new java.awt.Color(255, 0, 0));
        LabelFileName2.setText("Nome do arquivo . extesão");

        RadioButtonLogistic.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupFunction.add(RadioButtonLogistic);
        RadioButtonLogistic.setText("Logistica");

        jLabel1.setText("Taxa de aprendizado");

        TextFieldLearningRate.setText("0.35");
        TextFieldLearningRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldLearningRateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonInitTraining, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelFileName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelFileName2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonInitTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextFieldOcultLayer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel19)
                            .addComponent(jLabel23)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonChoseFile2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelClassAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelAttributesAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonChoseFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioButtonLogistic)
                            .addComponent(RadioButtonTH))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioButtonNumberIterations)
                            .addComponent(RadioButtonMaxError))
                        .addGap(32, 32, 32)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextFieldMaxError, javax.swing.GroupLayout.PREFERRED_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(TextFieldNumberOfIterations, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(TextFieldLearningRate)))
                .addGap(35, 35, 35))
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonChoseFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LabelFileName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(LabelAttributesAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(LabelClassAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(TextFieldOcultLayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioButtonLogistic)
                    .addComponent(RadioButtonMaxError)
                    .addComponent(TextFieldMaxError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioButtonTH)
                    .addComponent(RadioButtonNumberIterations)
                    .addComponent(TextFieldNumberOfIterations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextFieldLearningRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ButtonInitTraining, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(ButtonChoseFile2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelFileName2)
                .addGap(18, 18, 18)
                .addComponent(ButtonInitTest, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(88, 88, 88)
                        .addComponent(jLabel26)
                        .addGap(42, 42, 42))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonChoseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonChoseFileActionPerformed
        //Create a file chooser
        final JFileChooser fc = new JFileChooser();

        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            String fileName = file.getName();
            String filePath = file.getPath();
            LabelFileName.setText(fileName);

            ArrayList<ArrayList<Double>> matrixAttributes = ReaderCSV.reader(filePath);

            NN = new NeuralNetwork(matrixAttributes);

            LabelAttributesAmount.setText(String.valueOf(NN.getAttributesAmount()));
            LabelClassAmount.setText(String.valueOf(NN.getClassAmount()));
            TextFieldOcultLayer.setText(String.valueOf(NN.calculateNeuronsOcultLayer()));

            ButtonInitTraining.setEnabled(true);

        } else {
            System.out.println("Open command cancelled by user.");
        }

    }//GEN-LAST:event_ButtonChoseFileActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void ButtonChoseFile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonChoseFile2ActionPerformed
        //Create a file chooser
        final JFileChooser fc = new JFileChooser();

        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            String fileName = file.getName();
            String filePath = file.getPath();
            LabelFileName2.setText(fileName);

            matrixAttributesTest = ReaderCSV.reader(filePath);

            ButtonInitTest.setEnabled(true);

        } else {
            System.out.println("Open command cancelled by user.");
        }
    }//GEN-LAST:event_ButtonChoseFile2ActionPerformed

    private void TextFieldNumberOfIterationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNumberOfIterationsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNumberOfIterationsActionPerformed

    private void ButtonInitTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInitTrainingActionPerformed
        //definindo neuronios da camada oculta
        int neuronsOcultLayer = Integer.parseInt(TextFieldOcultLayer.getText());
        NN.setNeuronsOcultLayerAmount(neuronsOcultLayer);

        //definindo função que será usada
        if (RadioButtonLogistic.isSelected()) {
            NN.setFunction(0);
        } else {
            NN.setFunction(1);
        }

        //definindo condição de parada
        if (RadioButtonMaxError.isSelected()) {
            NN.setStop(0);
            NN.setStopNumber(Double.parseDouble(TextFieldMaxError.getText()));
        } else {
            NN.setStop(1);
            NN.setStopNumber(Integer.parseInt(TextFieldNumberOfIterations.getText()));
        }

        NN.setLearningRate(Double.parseDouble(TextFieldLearningRate.getText()));

        //Iniciando treinamento
        NN.initTraining();

        //Quanto o treinamento estiver completo habilitamos os botões para teste
        ButtonChoseFile2.setEnabled(true);
    }//GEN-LAST:event_ButtonInitTrainingActionPerformed

    private void ButtonInitTraining1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInitTraining1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonInitTraining1ActionPerformed

    private void RadioButtonTHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonTHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonTHActionPerformed

    private void RadioButtonNumberIterationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonNumberIterationsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonNumberIterationsActionPerformed

    private void RadioButtonMaxErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonMaxErrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonMaxErrorActionPerformed

    private void ButtonInitTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInitTestActionPerformed
        int[][] confusionMatrix = NN.test(matrixAttributesTest);

        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        for(int i = 0; i < confusionMatrix.length; i++){
            model.removeRow(0);
        }
        
        for(int i = 0; i < confusionMatrix.length; i++){
            Object[] row = new Object[confusionMatrix.length];
            for(int j = 0; j < confusionMatrix.length; j++){
                row[j] = (Object)confusionMatrix[i][j];
            }
            model.addRow(row);
        }
    }//GEN-LAST:event_ButtonInitTestActionPerformed

    private void TextFieldLearningRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldLearningRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldLearningRateActionPerformed

    private void TextFieldMaxErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldMaxErrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldMaxErrorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonChoseFile;
    private javax.swing.JButton ButtonChoseFile2;
    private javax.swing.JButton ButtonInitTest;
    private javax.swing.JButton ButtonInitTraining;
    private javax.swing.JLabel LabelAttributesAmount;
    private javax.swing.JLabel LabelClassAmount;
    private javax.swing.JLabel LabelFileName;
    private javax.swing.JLabel LabelFileName2;
    private javax.swing.JPanel Panel;
    private javax.swing.JRadioButton RadioButtonLogistic;
    private javax.swing.JRadioButton RadioButtonMaxError;
    private javax.swing.JRadioButton RadioButtonNumberIterations;
    private javax.swing.JRadioButton RadioButtonTH;
    private javax.swing.JTable Table;
    private javax.swing.JTextField TextFieldLearningRate;
    private javax.swing.JTextField TextFieldMaxError;
    private javax.swing.JTextField TextFieldNumberOfIterations;
    private javax.swing.JTextField TextFieldOcultLayer;
    private javax.swing.ButtonGroup buttonGroupFunction;
    private javax.swing.ButtonGroup buttonGroupParada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
